### ISSUE TITLE
dataset normalization

### ISSUE THREAD

**Issue by LogWell** [y-zheng18/MultiHuman-Dataset#1]
May I ask what operations are there for normalization, and what is the scaling ratio?

**Comment by y-zheng18** [comment]
To fit SMPL, the raw scans are normalized to about 1.7m. During reconstruction or calculating loss, each scan is normalized such that the height is 1m. You can see that those raw scans are tens of meters high, so the normalization is important.

**Comment by LogWell** [comment]
You can also use methods such as hmr for normalization, just curious why the result is not a normal height.

**Comment by y-zheng18** [comment]
Yeah of course you can use that. The normalization is to make sure the scans are with similar scale such that the reconstruction is performed under the same setting. Thanks for the comment.

**Comment by LogWell** [comment]
I mean, why is the dimension of raw data weird and not in meters or millimeters?

**Comment by y-zheng18** [comment]
well, the scans are captured by a dense camera rig, and I guess the camera parameters are not the same scale with the real world
