### ISSUE TITLE
Mask Generation for Real-world Capture

### ISSUE THREAD

**Issue by YoussefFathi** [y-zheng18/MultiHuman-Dataset#2]
I would like to ask whether the Segmentation masks (to segment humans from background) for the raw image sequences on Real World Capture are available or not? and if not any suggestions on how they could be reliably generated?

**Comment by y-zheng18** [comment]
I'm afraid the masks are not available now. But they can be easily generated using this [repo](https://github.com/GoGoDuck912/Self-Correction-Human-Parsing).
