### ISSUE TITLE
Cropped Video Sequences

### ISSUE THREAD

**Issue by YoussefFathi** [y-zheng18/MultiHuman-Dataset#3]
The video sequences provided for the Real World Capture dataset are cropped in the height dimension (i.e don't show the legs). On the other hand, the cropped images of each human show their full bodies. Is there a way to get the corresponding non-cropped full frames for all views?

**Comment by y-zheng18** [comment]
The videos in _xxx_original_video_ folder  should contain the full frames. Would you provide an example (e.g., a screenshot) of the problem?

**Comment by YoussefFathi** [comment]
This is a sample image from frame 434 for camera 0 in the *box* folder for person 1. It clearly shows the full body of the person.
![person_0_box](https://user-images.githubusercontent.com/31455775/169762876-432cb842-9451-479d-a1e6-9d2893bffbb7.jpg)

This is a sample frame from the  corresponding video for camera 0 in "box_original_video". It can be clearly seen that the video is cropped vertically and does not show the full human body like the image shown above.
![image](https://user-images.githubusercontent.com/31455775/169763090-14c0c2cc-ca7a-47b4-bae5-173e1fbb48be.png)

**Comment by YoussefFathi** [comment]
It turns out to be a problem with my local video player due to the videos being in 360 degrees mode. When I try extracting the independent frames, they are indeed full. Thanks.
