### ISSUE TITLE
Camera Calibration Files 

### ISSUE THREAD

**Issue by YoussefFathi** [y-zheng18/MultiHuman-Dataset#4]
In the Real World Capture dataset, the "calibration_new.json" files do not contain the distortion coefficients as part of the camera intrinsics. These coefficients are normally required by OpenCV to undistort the images as shown here https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html. Should we assume that there is no distortion in the case of those videos?

**Comment by y-zheng18** [comment]
The camera parameters in the file has been calibrated using the distortion parameters, so you can directly use the camera intrinsic and extrinsic matrix provided.
