### ISSUE TITLE
Weird Output When Generating 3D Keypoints

### ISSUE THREAD

**Issue by YoussefFathi** [y-zheng18/MultiHuman-Dataset#5]
I was trying to compute the 3D keypoints and SMPL models for all the frames of the Real World Capture dataset, however, the result I got shows the humans having keypoints below the ground which lies at z=0. Does this mean that the camera calibration was done while assuming that the world center is not at [0,0,0]? If this is the case then where does the world center lie?

I've included the following visualization to show the mentioned effect.
![image](https://user-images.githubusercontent.com/31455775/173007524-ffd2b15d-edfe-4357-9ddc-8d3b0dafa8c4.png)

**Comment by y-zheng18** [comment]
The system assumes the world center as the top left corner of the chessboard shown in the first calibration frame. It seems that the chessboard didn't lie on the floor when the first calibration frame was taken, so the coordinate system is a little bit weird. You can rotate the coordinate system manually and then use the rotation matrix to transform this coordinate system to canonical coordinate system.

**Comment by YoussefFathi** [comment]
Can you please elaborate more on how the coordinate system should be rotated manually to solve the problem?

**Comment by y-zheng18** [comment]
You can use blender for human annotation. For example, firstly load several estimated SMPL meshes in blender. Then you rotate and translate the meshes to make the people stand on the ground. You can get the transformation matrix from the translation and rotation parameters.

**Comment by yushanz** [comment]
> I was trying to compute the 3D keypoints and SMPL models for all the frames of the Real World Capture dataset, however, the result I got shows the humans having keypoints below the ground which lies at z=0. Does this mean that the camera calibration was done while assuming that the world center is not at [0,0,0]? If this is the case then where does the world center lie?
> 
> I've included the following visualization to show the mentioned effect. ![image](https://user-images.githubusercontent.com/31455775/173007524-ffd2b15d-edfe-4357-9ddc-8d3b0dafa8c4.png)

Hi, would you please elaborate more on how you managed to compute the 3D keypoints and SMPL models? I am quite confused about what to do. Thank you so much in advance for your help!!

**Comment by y-zheng18** [comment]
you can refer to this paper for smplx generation: http://www.liuyebin.com/lwtotalcap/lwtotalcap.html

**Comment by yushanz** [comment]
> you can refer to this paper for smplx generation: http://www.liuyebin.com/lwtotalcap/lwtotalcap.html

Thank you so much or the quick reply! Yes I have checked this paper but didn't find the code to reproduce the result. Is there any existing repository that has implemented the lightweight total motion capture already?
